### ISSUE TITLE
T2w scan 

### ISSUE THREAD

**Issue by a3sha2** [Cadaei-Yuvxvs/OSHy-X#16]
@Cadaei-Yuvxvs  is a T2w scan compulsory? 
what if there is no T2w?

**Comment by Cadaei-Yuvxvs** [comment]
Hi @a3sha2 thanks very much for your question. T2w is not compulsory. By default, OSHy-X accepts T1w images. However, the user can use the `--weighting` flag to specify if the input image is T2w instead.
