### ISSUE TITLE
test of tool usage in container

### ISSUE THREAD

**Issue by kaczmarj** [Cadaei-Yuvxvs/OSHy-X#7]
hello, i am reviewing the JOSS submission for this project at https://github.com/openjournals/joss-reviews/issues/4368#issuecomment-1116524168. this issue is related to my review.

i see the pytest tests to test the functionality of `OSHy.py`, but since this project is used through a container, it would be good to test the behavior in the container. for example, perhaps a sample image could be segmented, and assuming this is deterministic (i don't know if it is), the segmentations can be compared to a known state. this way, any regressions can be caught early.

**Comment by Cadaei-Yuvxvs** [comment]
Thank you Jakub. I will add a GitHub Actions workflow to address this.

**Comment by Cadaei-Yuvxvs** [comment]
Hi Jakub, a new job has been added to a GitHub actions workflow which tests the various pipelines offered by OSHyX using the container - the same way an end user would use OSHyX: https://github.com/Cadaei-Yuvxvs/OSHy-X/actions/workflows/test_oshyx.yml

**Comment by kaczmarj** [comment]
Hi @Cadaei-Yuvxvs - looks great!
