### ISSUE TITLE
comparison to freesurfer recon-all

### ISSUE THREAD

**Issue by kaczmarj** [Cadaei-Yuvxvs/OSHy-X#8]
hello, i am reviewing the JOSS submission for this project at https://github.com/openjournals/joss-reviews/issues/4368#issuecomment-1116524168. this issue is related to my review.

i assume that many neurimaging researchers use freesurfer's `recon-all` workflow to segment subcortical structures like the hypothalamus and fornix. given this, i think a comparison with `recon-all` should be included.

**Comment by Cadaei-Yuvxvs** [comment]
Thank you for the suggestion, Jakub. The hypothalamus is segmented in Freesurfer's `recon-all` using the method outlined by Billot _et al._. I will update the paper to clarify this. I will also add additional comparisons for fornix segmentation by `recon-all`.

**Comment by Cadaei-Yuvxvs** [comment]
Dear Jakub, I have now updated our JOSS paper draft to include comparisons with FreeSurfer's segmentation of the hypothalamus and fornix, however both structures are not segmented by default using the `recon-all` command. Instead, separate commands need to be called. Our comparisons indicate that Joint Label Fusion outperforms FreeSurfer for both structures at 3T and 7T field strengths. See https://github.com/openjournals/joss-reviews/issues/4368#issuecomment-1159648460

**Comment by kaczmarj** [comment]
@Cadaei-Yuvxvs - thank you for including the comparison. I'll close this now.
